### ISSUE TITLE
Solve the slow loading issue 

### ISSUE THREAD

**Issue by Sahar-behpour** [episphere/epitracker#103]
Loading is so slow, I think this is due to the libraries and also graying out the counties. The selections of counties is coming from a different file compare to the map data.

**Comment by LKMason** [comment]
Fixed with https://github.com/episphere/epitracker/pull/107 

Was due to a line that was inefficiently checking for counties in the dataset using an array ```find```. Switched to using a set. Also fixed this in the state selection, where there was an identical problem.
