### ISSUE TITLE
Confusing URLs due to hash param routing

### ISSUE THREAD

**Issue by Sahar-behpour** [episphere/epitracker#111]
Do not included the the default selections in URL. Also, do not put the URL between 
http://localhost:8002/

**Comment by LKMason** [comment]
Default selections are no longer included in the URL, fixed by the code-refactor branch. 

However, the latter problem persists and may be challenging to fix due to how hash and search params are handled. I think the main issue is how routing is handled. It shouldn't use hash params.

**Comment by LKMason** [comment]
Fixed with https://github.com/episphere/epitracker/pull/202
