### ISSUE TITLE
 more options for quantiles

### ISSUE THREAD

**Issue by Sahar-behpour** [episphere/epitracker#116]
Can we add an option to have more options for quantiles? Maybe 4, 6, 8 and 10?

**Comment by LKMason** [comment]
I think the best would be 4, 5, and 10. Quartiles, quintiles, and deciles are standard in the field. I don't believe octiles are, but they are nice balance IMO. We should discuss.

**Comment by Sahar-behpour** [comment]
New issues are created for this based on the feedbacks
