### ISSUE TITLE
quantile visualization error

### ISSUE THREAD

**Issue by jonasalmeida** [episphere/epitracker#16]
when https://episphere.github.io/epitracker/#quantile-visualization the rendering fails. This is not a problem in incognito mode. This looks like a persistent storage error associated with WorkBox. This is not the first project where I see WorkBox have sticking behaviors. Is it worth the trouble?

![Screenshot 2023-06-15 at 3 40 01 PM](https://github.com/episphere/epitracker/assets/204769/18082fad-e19b-421b-b161-59041f003f1a)

Note also unresolvable https://episphere.github.io/src/pages/homePage.js

**Comment by bkop-ds** [comment]
Went ahead and removed the caching feature. I also added code to automatically delete the serviceWorker for users that already have it. Seems overkill to have this, as of now, especially as we are making constant updates. I will leave this open just to confirm later today that it works.
