### ISSUE TITLE
When cause: "eye and orbit", none of the states has data for it. Should we gray it out or show a note like " Data is not available for this selection of cause"

### ISSUE THREAD

**Issue by Sahar-behpour** [episphere/epitracker#172]
When cause: eye and orbit, none of the states has data for it. Should we gray it out or have a note on the page " Data is not available for this selection of cause"

**Comment by LKMason** [comment]
Eye and orbit is such an uncommon cancer that it only has data at the state level. The system already shows a "No Data" message, so I think we're fine here. 

Perhaps we could consider greying out selections again, as an enhancement. I've made a new issue to capture that: https://github.com/episphere/epitracker/issues/196
