### ISSUE TITLE
On map page, allow multi-selection for stratified variables

### ISSUE THREAD

**Issue by LKMason** [episphere/epitracker#180]
Currently, if the user stratifies by a field (e.g. Race) then the select box greys out (because it doesn't make the same sense it used to). Instead, we should consider turning the select box into a multi-select, and allowing the user to just remove the maps they don't want.

Alternatively, we could have a button beside the "download" button on the map itself which allows the user to hide it.

**Comment by Sahar-behpour** [comment]
race box should be searchable and multirecelction

**Comment by LKMason** [comment]
We've discussed quite a few options for this. The general consensus is that direct control (a button to hide a row or column NEAR the plot that is to be hidden) is better than a dropdown or other control in the side or top bar.

Not sure exactly how this should look.
