### ISSUE TITLE
Does the state of a page persist between pages?

### ISSUE THREAD

**Issue by LKMason** [episphere/epitracker#186]
I've noticed that the state of a page seems to persist when changing pages. e.g. if I go on the map page, then when I go to the quantile page the state of the map page is preserved. This wouldn't be good for memory management and I don't think this approach is needed for this application. Just making this issue to confirm if this is the case, and to fix it later if so.

**Comment by LKMason** [comment]
This would be fixed by https://github.com/episphere/epitracker/issues/87

**Comment by Saharbehpour** [comment]
I no longer see this issue
