### ISSUE TITLE
dev and prod version simultaneously visible in gh-pages (i.e. served as github.io)

### ISSUE THREAD

**Issue by jonasalmeida** [episphere/epitracker#2]
I am not sure we can rely on branches alone to keep both a dev (or more) and a prod version since gh-pages requires you to pick which branch is served. And on top of that Lee's early experiments would be buried. Should we have an epitracker-dev and (forked?) and epitracker-prod rep?

**Comment by LKMason** [comment]
One crude way to keep multiple versions alive is to have them in different folders. The root index page could be the latest version, and older versions could be in sub-directories (e.g. https://episphere.github.io/epitracker/demo01). This would work for static versions but would need to be handled manually and wouldn't take full advantage of the versioning control.

**Comment by bkop-ds** [comment]
we could give the multiple folders a try, it would still involve the user getting directed to the version they want. Two reps would be the cleanest option, then Lee's code would always be standalone and easily accessible.
