### ISSUE TITLE
Drop some county level factors please

### ISSUE THREAD

**Issue by meredithshiels** [episphere/epitracker#219]
[county level measures_drop_01feb24.csv](https://github.com/episphere/epitracker/files/14130486/county.level.measures_drop_01feb24.csv)
Please drop the county-level factors marked with an X on the attached spreadsheet.

Thank you!

**Comment by meredithshiels** [comment]
Also please drop drinking water violations. This is a yes/no variable so it does not work in a quantile scale.

**Comment by Saharbehpour** [comment]
Remove from the whole dataset

**Comment by Sahar-behpour** [comment]
Removed those factors, kept the old data into the quantile data folder. Pushed and merged the code.
