### ISSUE TITLE
Maps: color scale

### ISSUE THREAD

**Issue by Peter-Kraft** [episphere/epitracker#22]
The color scale extends below 0 for age-adjusted and crude rates. Deep blue never occurs b/c it's a negative value. In fact, if you look at all age-adjusted all-cause mortality and select sex=M, the legend includes -2000. Does not look like any negative value is getting plotted (that's good), but seeing a (large) negative value on the legend looks odd.

**Comment by Peter-Kraft** [comment]
Ah, the color centering is clever. (2) sounds worth a try.

**Comment by LKMason** [comment]
I've fixed this by adding a custom color legend component which only spans the range of values. More details here: https://observablehq.com/d/95596fe7a581a658
