### ISSUE TITLE
Remove age_adjusted field in the table when showing age_group on demographics page

### ISSUE THREAD

**Issue by LKMason** [episphere/epitracker#288]

**Comment by Sahar-behpour** [comment]
For the None-None selection, what should we present in the table?

**Comment by LKMason** [comment]
This should be the logic: if "Age group" is selected in either of the compare selections OR if a specific age group is selected in the "Age group" filter selection, then hide the age-adjusted mortality rates from the table and the measure selection. No other conditions are needed.
