### ISSUE TITLE
Liver Death Issue

### ISSUE THREAD

**Issue by DrMcAvila** [episphere/epitracker#323]
Hi, 
When I'm looking at certain indicators in relation to liver death, Im getting errors messages for some (median household income) and nothing populating at all (for severe housing cost burden). 
<img width="1361" alt="Screenshot 2024-05-28 at 9 44 25 AM" src="https://github.com/episphere/epitracker/assets/170967573/f24616fe-8129-4836-8597-e91eb9f9d795">

**Comment by Sahar-behpour** [comment]
There was a bug that was coming from "-" and that got resolved
