### ISSUE TITLE
Less overwhelming tooltips

### ISSUE THREAD

**Issue by LKMason** [episphere/epitracker#37]
I think the tooltip on the map displays too much information. At the very least, it shouldn't display information that is present in the selections (like sex, race, and cause) because that information is known to the user and doesn't change by area. We should discuss what we want to include, but I think it should be something like:

[Full area name (e.g. Mason, TX)]
[Selected measure (e.g. age-adjusted mortality)]

Maybe with population.

**Comment by Sahar-behpour** [comment]
A tooltip is created, but we might need a hit presenting on the page so that the users can be aware of such functionality.

**Comment by LKMason** [comment]
Fixed in #83
