### ISSUE TITLE
Color scales should be map specific

### ISSUE THREAD

**Issue by meredithshiels** [episphere/epitracker#379]
I think that the scales for the maps should be map-specific. Right now there is only one scale, and some of the maps are based on different metrics (e.g., #deaths vs. crude rates)

**Comment by LKMason** [comment]
It will be challenging to position a unique color legend on each map, and it will also make it difficult to compare values from different demographic groups. We should discuss this at the next meeting.

**Comment by LKMason** [comment]
We discussed this in the meeting and decided to keep the shared color scheme, but remove the ability to select distinct measures for cards. Measure will now be a global property.
