### ISSUE TITLE
Bug in the map

### ISSUE THREAD

**Issue by Sahar-behpour** [episphere/epitracker#383]
If a user keeps adding cards , without submitting their selections, or without editing a card, the first map gets hided under the box around it, and it one of the cars is edited, the resulted map appears similarly. 
![image](https://github.com/user-attachments/assets/cb04e0d5-7aa7-4493-b8d5-bd7245b77a49)

**Comment by LKMason** [comment]
Is this the same as https://github.com/episphere/epitracker/issues/385 ?

**Comment by Sahar-behpour** [comment]
> Is this the same as #385 ?

It was  appearing in different a different scenario compared to the other issue. But it is resolved and I am closing it.
