### ISSUE TITLE
Improve quantile page decimal places

### ISSUE THREAD

**Issue by meredithshiels** [episphere/epitracker#452]
On the quantile page, could you please edit the decimal places as follows: 

3 integers or more - no decimal places (xxx)
2 integers - one decimal place (xx.x)
1 integer or <1 - two decimal places (x.xx or 0.xx)

@LKMason - could you please elevate this?

**Comment by LKMason** [comment]
We should discuss this one. I am not sure it is necessarily good practice to have decimals that indicate a greater degree of precision than present in the dataset.

**Comment by meredithshiels** [comment]
Lee - I'm happy to have you make other suggestions for this. Sig figs sounds great, but you are right, if there is no decimal data, we should just round to whole numbers.

**Comment by LKMason** [comment]
Going with 2 sig figs for now.
