### ISSUE TITLE
Filtering gender when choosing cancer protests 

### ISSUE THREAD

**Issue by Sahar-behpour** [episphere/epitracker#46]
When cancer prostate is chosen, and compare secondary is sex, then in the select part, gender is chosen female, we get blank. Or if they compare primary and secondary are based on race and gender, even if we chose female, we still see some graphs which are only related to male. We should fix this by either showing a message that there is no data available for this type of cancer for female, or we should adjust the filtering options of select or compare primary/secondary.

**Comment by LKMason** [comment]
Should be fixed with the new state model
