### ISSUE TITLE
Remove + tidy legacy confluence stuff

### ISSUE THREAD

**Issue by LKMason** [episphere/epitracker#48]
There's a lot of stuff still remaining from Confluence, we should remove this to keep the code tidy. There are also odd things that are linked to the legacy reliance on the previous framework, like defining the HTML documents in JS files. We should discuss if this is necessary because if not I think we should put them into HTML documents. 

The folder structure should be re-examined when this is done.

**Comment by bkop-ds** [comment]
Legacy Confluence codebase has been removed from. All previous mentions of confluence are now epitracker. Will create a separate issue for the HTML being defined in JS.
