### ISSUE TITLE
Should we continue to explicitly include "non-hispanic" in race/ethnicity labels?

### ISSUE THREAD

**Issue by LKMason** [episphere/epitracker#481]
In the tool and underlying datasets, we refer to the non-hispanic race/ethnicity groups with the label of "non-hispanic [blank]" or "blank (NH)". This is to explicitly convey that these groups explicitly don't include people with Hispanic ethnicity. However, it's verbose and a little difficult to work with in the dataset.  Because we call the field "race/ethnicity" and because we have a Hispanic group, is it OK to not explicitly include "non-hispanic" in these group names as long as it is explained elsewhere.

The main disadvantage for this would be when filtering in such a way that the "Hispanic" group is not visible.

**Comment by LKMason** [comment]
@meredithshiels Thoughts?

**Comment by meredithshiels** [comment]
@LKMason I think you can exclude "non-Hispanic" from the labels. We can be sure the mention this in the text on the webpage.

**Comment by LKMason** [comment]
Removed in https://github.com/episphere/epitracker/pull/496
