### ISSUE TITLE
Consistent color map for categories

### ISSUE THREAD

**Issue by LKMason** [episphere/epitracker#72]
Right now colors are assigned arbitrarily for categorical data. We should have a consistent set of colors so that "Male" is always one color, and "Black or African American" is always one color, etc.

**Comment by LKMason** [comment]
This will also fix a minor bug where "White" is interpreted as a color, which happens when "White" is the only value for a race stratification. This will also fix #67

**Comment by LKMason** [comment]
I don't think this issue is fixed, the color codings for races are still inconsistent on the demographics page, for example.

**Comment by Sahar-behpour** [comment]
This issue is fixed by correcting the color codes
