### ISSUE TITLE
Add data and SVG download button

### ISSUE THREAD

**Issue by LKMason** [episphere/epitracker#8]
The tool needs buttons to download the data and to download the plots in various image formats. I like [the way IARC does it](https://gco.iarc.fr/today/online-analysis-treemap), with a toolbar anchored to the right of the screen. This would be easy to implement. Another approach would be to have a fading in menu on each plot, like how Plotly does it. This would be good for downloading individual plots as images or if different plots have different data (not sure this will happen). I have [a notebook](https://observablehq.com/d/928f5b81479b7c1a) from a while ago where I experimented with that, to do it properly it would be better that a bar with multiple buttons fades in and out. It should also be positioned outside the plot content. 

I think we should take the former approach for now.

**Comment by Sahar-behpour** [comment]
Working on it.

**Comment by Sahar-behpour** [comment]
Completed. Might need improvements in the designed icons.
