### ISSUE TITLE
Tidy zoom and pan code

### ISSUE THREAD

**Issue by LKMason** [episphere/epitracker#97]
Basics of zoom and pan are there, but could perhaps do with some tidying:

* Slightly off center, perhaps due to zoom scale parameter (which we base relative to width, not sure what is actually correct)
* Lines perhaps too large on zoom
* Coloring individual counties seems a bit pointless, let's just zoom in one them and keep their state colored?
* Ability to lock pan-and-zoom

**Comment by Sahar-behpour** [comment]
Ability to lock pan-and-zoom is done.
